[project]
name = "creative-automation-pipeline"
version = "0.1.0"
description = "Enterprise creative automation pipeline"
requires-python = ">=3.9,<3.14"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py313"
