name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint (ruff + black --check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black
      - name: Ruff
        run: ruff check .
      - name: Black (check only)
        run: black --check .

  tests:
    name: Tests (pytest if present)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests if tests/ exists
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests directory; skipping."
          fi

  provider-smoke:
    name: Provider secrets check (no API calls)
    if: ${{ secrets.OPENAI_API_KEY != '' || secrets.STABILITY_API_KEY != '' }}
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dotenv
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
      - name: Report secrets presence (safe)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: |
          python - <<'PY'
import os
print("OpenAI key present:", bool(os.getenv("OPENAI_API_KEY")))
print("Stability key present:", bool(os.getenv("STABILITY_API_KEY")))
PY
